# Generated by Django 3.0.6 on 2020-06-01 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_auto_20200525_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'Employee_details'},
        ),
    ]
